# Generated by Django 2.1 on 2018-10-09 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('who_is', '0006_auto_20181005_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('date', models.DateTimeField()),
                ('result', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='gameround',
            name='date',
        ),
        migrations.RemoveField(
            model_name='gameround',
            name='time',
        ),
        migrations.RemoveField(
            model_name='gameround',
            name='usr_info',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='sex',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1),
        ),
        migrations.AddField(
            model_name='game',
            name='usr_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_round', to='who_is.UserInfo'),
        ),
        migrations.AddField(
            model_name='gameround',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_round', to='who_is.Game'),
        ),
    ]
