# Generated by Django 2.1 on 2018-10-09 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('who_is', '0007_auto_20181009_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='usr_info',
        ),
        migrations.AddField(
            model_name='game',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game', to=settings.AUTH_USER_MODEL),
        ),
    ]
