# Generated by Django 2.1 on 2018-10-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('who_is', '0009_auto_20181009_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
